# Generated by Django 5.1.4 on 2024-12-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_app', '0002_apartment_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_set', to='apartments_app.apartment'),
        ),
    ]
