# Generated by Django 5.1.4 on 2024-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_app', '0004_inquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
    ]
